name: animal-faces-classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch
    - torchvision
    - "numpy<2.0"
    - pandas
    - matplotlib
    - scikit-learn
    - kaggle
    - opendatasets
    - torchinfo